export const Users = [
    {
      id:1,
      postProfilePic: "collect/person/04.jpg",
      username: "Raj Agrawal",
    },
    {
      id:2,
      postProfilePic: "collect/person/02.jpg",
      username: "Anjali Naik ",
    },
    {
      id:3,
      postProfilePic: "collect/person/05.jpg",
      username: "Rajeev Sharma",
    },
    {
      id:4,
      postProfilePic: "collect/person/11.jpg",
      username: "Anushka Jain",
    },
    {
      id:5,
      postProfilePic: "collect/person/12.jpg",
      username: "Hamza Saifi",
    },
    {
      id:6,
      postProfilePic: "collect/person/01.jpg",
      username: "Hala Hameed",
    },
    {
      id:7,
      postProfilePic: "collect/person/13.jpg",
      username: "Dalmi Seo",
    },
    {
      id:8,
      postProfilePic: "collect/person/14.jpg",
      username: "Nam Dosan ",
    },
    {
      id:9,
      postProfilePic: "collect/person/15.jpg",
      username: "Sellly Herlay",
    },
    {
      id:10,
      postProfilePic: "collect/person/16.jpg",
      username: "Hamsha Qazi",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      des: "Love For All, Hatred For None.",
      photo: "collect/post/01.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 78,
      comment: 9,
    },
    {
      id: 2,
      des: "Change the world by being yourself.",
      photo: "collect/post/02.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 6,
      comment: 32,
    },
    {
      id: 3,
      des: " Just pick up your Camera and see this beautiful world!!",
      photo: "collect/post/03.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 64,
      comment: 2,
    },
    {
      id: 4,
      des: " Exploring something new ,love it.",
      photo: "collect/post/04.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 76,
      comment: 21,
    },
    {
      id: 5,
      des: "Be strong  , be happy , be yourself.",
      photo: "collect/post/05.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 15,
    },
    {
      id: 6,
      des: "Love this new style of my couch.",
      photo: "collect/post/06.jpg",
      date: "1 day ago",
      userId: 6,
      like: 79,
      comment: 6,
    },
    {
      id: 7,
      des: "Never regret anything that made you smile.",
      photo: "collect/post/07.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 23,
    },
    {
      id: 8,
      des: "Let's make future.",
      photo: "collect/post/08.jpg",
      date: "3 days ago",
      userId: 8,
      like: 56,
      comment: 11,
    },
    {
      id: 9,
      des: "sometimes change is essential to know the flow.",
      photo: "collect/post/09.jpg",
      date: "5 days ago",
      userId: 9,
      like: 30,
      comment: 12,
    },
    {
      id: 10,
      des: "Every moment is a fresh beginning.",
      photo: "collect/post/10.jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];